name: CI

on:
#   push:
#     branches: [ master ]
# unnecessary?
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run tests
      run: cargo test --verbose