name: CI

on:
#   push:
#     branches: [ master ]
# unnecessary?
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
    - uses: actions/checkout@v2

    - name: Run tests
      run: cargo test --verbose